# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# 共通設定
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# 開発環境
development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

# テスト環境
test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

# 本番環境
production:
  <<: *default
  adapter: mysql2
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
